version: '3.7'
services:
  database:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: wm
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: wm-web-client-db