# Generated by Django 3.2.5 on 2021-10-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminsession',
            table='wm_admin_session',
        ),
    ]
