"""
Django settings for caveServer project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from . import env

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.SIGNATURE

APPEND_SLASH = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.PROFILE.lower() != 'prod'

ALLOWED_HOSTS = ["*", "localhost", "0.0.0.0", "127.0.0.1"]

# Application definition
INSTALLED_APPS = [
    'common',
    'administrator',
    'client',
    'django.contrib.contenttypes',
    'django.contrib.sessions'
]

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'resources/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request'            ],
        },
    },
]

WSGI_APPLICATION = 'parent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, 'parent', '../resources/env', f'{env.PROFILE}', '.my.cnf')
        }
    }
}

# Session
SESSION_COOKIE_HTTPONLY = True
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_AGE = 300
SESSION_COOKIE_NAME = 'signature'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'es-ar'
USE_I18N = True
USE_L10N = True
USE_TZ = True
TIME_ZONE = 'America/Argentina/Buenos_Aires'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'resources/static')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'resources/media')

STATICFILES_DIR = (
    ('/static', os.path.join(BASE_DIR, 'resources/static')),
    ('/media', os.path.join(BASE_DIR, 'resources/media')),
    ('favicon.ico', os.path.join(BASE_DIR, 'resources/static/images/favicon.ico'))
)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "[%(asctime)s] - %(name)-s - %(levelname)-s - %(lineno)d - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S"
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
            "level": "DEBUG",
            "stream": "ext://sys.stdout"
        }
    },
    "loggers": {
        "console": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": True
        }
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console'],
        'propagate': True
    }
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440 * 100
